# Generated by Django 5.0.1 on 2024-01-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='header/', verbose_name='header logo')),
                ('name', models.CharField(max_length=250, verbose_name='header name')),
                ('page1', models.CharField(max_length=250, verbose_name='page1 name')),
                ('page2', models.CharField(max_length=250, verbose_name='page2 name')),
                ('page3', models.CharField(max_length=250, verbose_name='page3 name')),
                ('search', models.CharField(max_length=250, verbose_name='search name')),
                ('search_logo', models.ImageField(upload_to='header/', verbose_name='search_logo')),
                ('currency_logo', models.ImageField(upload_to='header/', verbose_name='currency_logo')),
                ('language_logo', models.ImageField(upload_to='header/', verbose_name='language_logo')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
