# Generated by Django 5.0.2 on 2024-03-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additional',
            name='add_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='additional name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='add_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='additional name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='add_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='additional name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='requirements name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='requirements name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='requirements name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='winter_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='winter name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='winter_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='winter name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='winter_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='winter name'),
        ),
    ]
