# Generated by Django 5.0.2 on 2024-03-08 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_additional_add_name_en_additional_add_name_hy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='choice_pro', to='main.choice'),
            preserve_default=False,
        ),
    ]
