# Generated by Django 5.0.2 on 2024-03-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_header_currency_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='act_car_logo',
            field=models.ImageField(default=1, upload_to='Choise/', verbose_name='active car image'),
            preserve_default=False,
        ),
    ]
