# Generated by Django 5.0.2 on 2024-03-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_cost_cost_name_alter_cost_cost_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='spet_about',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='spet_about_en',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='spet_about_hy',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='spet_about_ru',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='spet_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='spet_name_en',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='spet_name_hy',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='spet_name_ru',
        ),
        migrations.AddField(
            model_name='reservation',
            name='air_about',
            field=models.CharField(max_length=250, null=True, verbose_name='air_conditioner about'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='air_about_en',
            field=models.CharField(max_length=250, null=True, verbose_name='air_conditioner about'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='air_about_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='air_conditioner about'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='air_about_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='air_conditioner about'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='air_name',
            field=models.CharField(max_length=250, null=True, verbose_name='air_conditioner name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='air_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='air_conditioner name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='air_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='air_conditioner name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='air_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='air_conditioner name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='engine_about',
            field=models.CharField(max_length=250, null=True, verbose_name='engine about'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='engine_about_en',
            field=models.CharField(max_length=250, null=True, verbose_name='engine about'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='engine_about_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='engine about'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='engine_about_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='engine about'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='engine_name',
            field=models.CharField(max_length=250, null=True, verbose_name='engine name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='gear_about',
            field=models.CharField(max_length=250, null=True, verbose_name='gear_box about'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='gear_about_en',
            field=models.CharField(max_length=250, null=True, verbose_name='gear_box about'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='gear_about_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='gear_box about'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='gear_about_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='gear_box about'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='gear_name',
            field=models.CharField(max_length=250, null=True, verbose_name='gear_box name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='gear_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='gear_box name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='gear_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='gear_box name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='gear_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='gear_box name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_about',
            field=models.BigIntegerField(null=True, verbose_name='number_seats number'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_name',
            field=models.CharField(max_length=250, null=True, verbose_name='number_seats name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='number_seats name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='number_seats name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='number_seats name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='roof_about',
            field=models.CharField(max_length=250, null=True, verbose_name='roof about'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='roof_about_en',
            field=models.CharField(max_length=250, null=True, verbose_name='roof about'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='roof_about_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='roof about'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='roof_about_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='roof about'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='roof_name',
            field=models.CharField(max_length=250, null=True, verbose_name='roof name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='roof_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='roof name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='roof_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='roof name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='roof_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='roof name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='year_about',
            field=models.CharField(max_length=250, null=True, verbose_name='year_manufacture about'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='year_about_en',
            field=models.CharField(max_length=250, null=True, verbose_name='year_manufacture about'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='year_about_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='year_manufacture about'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='year_about_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='year_manufacture about'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='year_name',
            field=models.CharField(max_length=250, null=True, verbose_name='year_manufacture name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='year_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='year_manufacture name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='year_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='year_manufacture name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='year_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='year_manufacture name'),
        ),
    ]
