# Generated by Django 5.0.1 on 2024-01-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='product name')),
                ('name_hy', models.CharField(max_length=250, null=True, verbose_name='product name')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='product name')),
                ('name_en', models.CharField(max_length=250, null=True, verbose_name='product name')),
                ('button_name', models.CharField(max_length=250, verbose_name='button name')),
                ('button_name_hy', models.CharField(max_length=250, null=True, verbose_name='button name')),
                ('button_name_ru', models.CharField(max_length=250, null=True, verbose_name='button name')),
                ('button_name_en', models.CharField(max_length=250, null=True, verbose_name='button name')),
                ('pleace_name', models.CharField(max_length=250, verbose_name='pleace name')),
                ('pleace_name_hy', models.CharField(max_length=250, null=True, verbose_name='pleace name')),
                ('pleace_name_ru', models.CharField(max_length=250, null=True, verbose_name='pleace name')),
                ('pleace_name_en', models.CharField(max_length=250, null=True, verbose_name='pleace name')),
                ('pleace_logo', models.ImageField(upload_to='Product/', verbose_name='place image')),
                ('car_name', models.CharField(max_length=250, verbose_name='car name')),
                ('car_name_hy', models.CharField(max_length=250, null=True, verbose_name='car name')),
                ('car_name_ru', models.CharField(max_length=250, null=True, verbose_name='car name')),
                ('car_name_en', models.CharField(max_length=250, null=True, verbose_name='car name')),
                ('car_logo', models.ImageField(upload_to='Product/', verbose_name='car image')),
                ('speed_name', models.CharField(max_length=250, verbose_name='speed name')),
                ('speed_name_hy', models.CharField(max_length=250, null=True, verbose_name='speed name')),
                ('speed_name_ru', models.CharField(max_length=250, null=True, verbose_name='speed name')),
                ('speed_name_en', models.CharField(max_length=250, null=True, verbose_name='speed name')),
                ('speed_logo', models.ImageField(upload_to='Product/', verbose_name='speed image')),
                ('gearbox_name', models.CharField(max_length=250, verbose_name='gearbox name')),
                ('gearbox_name_hy', models.CharField(max_length=250, null=True, verbose_name='gearbox name')),
                ('gearbox_name_ru', models.CharField(max_length=250, null=True, verbose_name='gearbox name')),
                ('gearbox_name_en', models.CharField(max_length=250, null=True, verbose_name='gearbox name')),
                ('gearbox_logo', models.ImageField(upload_to='Product/', verbose_name='gearbox image')),
                ('person_name', models.CharField(max_length=250, verbose_name='person name')),
                ('person_name_hy', models.CharField(max_length=250, null=True, verbose_name='person name')),
                ('person_name_ru', models.CharField(max_length=250, null=True, verbose_name='person name')),
                ('person_name_en', models.CharField(max_length=250, null=True, verbose_name='person name')),
                ('person_logo', models.ImageField(upload_to='Product/', verbose_name='person image')),
                ('fuel_name', models.CharField(max_length=250, verbose_name='fuel name')),
                ('fuel_name_hy', models.CharField(max_length=250, null=True, verbose_name='fuel name')),
                ('fuel_name_ru', models.CharField(max_length=250, null=True, verbose_name='fuel name')),
                ('fuel_name_en', models.CharField(max_length=250, null=True, verbose_name='fuel name')),
                ('fuel_logo', models.ImageField(upload_to='Product/', verbose_name='fuel image')),
                ('car_button', models.CharField(max_length=250, verbose_name='button name')),
                ('car_button_hy', models.CharField(max_length=250, null=True, verbose_name='button name')),
                ('car_button_ru', models.CharField(max_length=250, null=True, verbose_name='button name')),
                ('car_button_en', models.CharField(max_length=250, null=True, verbose_name='button name')),
                ('price', models.BigIntegerField(verbose_name='rent price')),
                ('price_text', models.CharField(max_length=250, verbose_name='price about')),
                ('price_text_hy', models.CharField(max_length=250, null=True, verbose_name='price about')),
                ('price_text_ru', models.CharField(max_length=250, null=True, verbose_name='price about')),
                ('price_text_en', models.CharField(max_length=250, null=True, verbose_name='price about')),
            ],
        ),
    ]
