# Generated by Django 5.0.2 on 2024-03-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_reservation_spet_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='cost_name',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='cost_name_en',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='cost_name_hy',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='cost_name_ru',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='cost_num',
        ),
        migrations.AddField(
            model_name='cost',
            name='del_name',
            field=models.CharField(max_length=250, null=True, verbose_name='deliveri name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='del_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='deliveri name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='del_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='deliveri name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='del_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='deliveri name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='del_num',
            field=models.IntegerField(null=True, verbose_name='delivery price'),
        ),
        migrations.AddField(
            model_name='cost',
            name='deposit_name',
            field=models.CharField(max_length=250, null=True, verbose_name='deposit name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='deposit_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='deposit name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='deposit_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='deposit name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='deposit_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='deposit name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='deposit_num',
            field=models.IntegerField(null=True, verbose_name='deposit price'),
        ),
        migrations.AddField(
            model_name='cost',
            name='drop_name',
            field=models.CharField(max_length=250, null=True, verbose_name='drop_off name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='drop_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='drop_off name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='drop_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='drop_off name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='drop_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='drop_off name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='drop_num',
            field=models.IntegerField(null=True, verbose_name='drop_off price'),
        ),
        migrations.AddField(
            model_name='cost',
            name='free_name',
            field=models.CharField(max_length=250, null=True, verbose_name='free_cancellation name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='free_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='free_cancellation name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='free_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='free_cancellation name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='free_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='free_cancellation name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='free_num',
            field=models.IntegerField(null=True, verbose_name='free_cancellation price'),
        ),
        migrations.AddField(
            model_name='cost',
            name='other_name',
            field=models.CharField(max_length=250, null=True, verbose_name='other name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='other_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='other name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='other_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='other name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='other_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='other name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='pay_name',
            field=models.CharField(max_length=250, null=True, verbose_name='to_pay name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='pay_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='to_pay name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='pay_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='to_pay name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='pay_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='to_pay name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='pay_num',
            field=models.IntegerField(null=True, verbose_name='to_pay price'),
        ),
        migrations.AddField(
            model_name='cost',
            name='pick_name',
            field=models.CharField(max_length=250, null=True, verbose_name='pick_up name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='pick_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='pick_up name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='pick_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='pick_up name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='pick_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='pick_up name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='pick_num',
            field=models.IntegerField(null=True, verbose_name='pick_up price'),
        ),
        migrations.AddField(
            model_name='cost',
            name='rent_name',
            field=models.CharField(max_length=250, null=True, verbose_name='rent_for name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='rent_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='rent_for name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='rent_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='rent_for name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='rent_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='rent_for name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='rent_num',
            field=models.IntegerField(null=True, verbose_name='rent_for price'),
        ),
        migrations.AddField(
            model_name='cost',
            name='total_name',
            field=models.CharField(max_length=250, null=True, verbose_name='total name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='total_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='total name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='total_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='total name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='total_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='total name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='total_num',
            field=models.IntegerField(null=True, verbose_name='total price'),
        ),
        migrations.AddField(
            model_name='cost',
            name='tpl_name',
            field=models.CharField(max_length=250, null=True, verbose_name='tpl name'),
        ),
        migrations.AddField(
            model_name='cost',
            name='tpl_num',
            field=models.IntegerField(null=True, verbose_name='tpl price'),
        ),
    ]
