# Generated by Django 5.0.2 on 2024-03-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_cost_cost_name_remove_cost_cost_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirements',
            name='req_name',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='req_name_en',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='req_name_hy',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='req_name_ru',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='req_num',
        ),
        migrations.AddField(
            model_name='requirements',
            name='drivers_name',
            field=models.CharField(max_length=250, null=True, verbose_name='drivers name'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='drivers_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='drivers name'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='drivers_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='drivers name'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='drivers_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='drivers name'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='drivers_num',
            field=models.CharField(max_length=250, null=True, verbose_name='drivers about'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='drivers_num_en',
            field=models.CharField(max_length=250, null=True, verbose_name='drivers about'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='drivers_num_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='drivers about'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='drivers_num_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='drivers about'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='mil_name',
            field=models.CharField(max_length=250, null=True, verbose_name='mileage name'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='mil_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='mileage name'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='mil_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='mileage name'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='mil_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='mileage name'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='mil_num',
            field=models.CharField(max_length=250, null=True, verbose_name='mileage about'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='mil_num_en',
            field=models.CharField(max_length=250, null=True, verbose_name='mileage about'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='mil_num_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='mileage about'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='mil_num_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='mileage about'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='min_name',
            field=models.CharField(max_length=250, null=True, verbose_name='minimum_driving name'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='min_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='minimum_driving name'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='min_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='minimum_driving name'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='min_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='minimum_driving name'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='min_num',
            field=models.CharField(max_length=250, null=True, verbose_name='minimum_driving about'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='min_num_en',
            field=models.CharField(max_length=250, null=True, verbose_name='minimum_driving about'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='min_num_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='minimum_driving about'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='min_num_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='minimum_driving about'),
        ),
    ]
