# Generated by Django 5.0.2 on 2024-03-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_requirements_req_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additional',
            name='add_num',
        ),
        migrations.AddField(
            model_name='additional',
            name='booster_name',
            field=models.CharField(max_length=250, null=True, verbose_name='child_booster name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='booster_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='child_booster name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='booster_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='child_booster name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='booster_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='child_booster name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='booster_num',
            field=models.CharField(max_length=250, null=True, verbose_name='child_booster price'),
        ),
        migrations.AddField(
            model_name='additional',
            name='geo_name',
            field=models.CharField(max_length=250, null=True, verbose_name='georgia name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='geo_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='georgia name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='geo_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='georgia name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='geo_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='georgia name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='geo_num',
            field=models.CharField(max_length=250, null=True, verbose_name='georgia price'),
        ),
        migrations.AddField(
            model_name='additional',
            name='router_name',
            field=models.CharField(max_length=250, null=True, verbose_name='wifi_router name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='router_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='wifi_router name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='router_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='wifi_router name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='router_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='wifi_router name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='router_num',
            field=models.CharField(max_length=250, null=True, verbose_name='wifi_router price'),
        ),
        migrations.AddField(
            model_name='additional',
            name='safeti_name',
            field=models.CharField(max_length=250, null=True, verbose_name='child_safeti name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='safeti_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='child_safeti name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='safeti_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='child_safeti name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='safeti_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='child_safeti name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='safeti_num',
            field=models.CharField(max_length=250, null=True, verbose_name='child_safeti price'),
        ),
        migrations.AddField(
            model_name='additional',
            name='seat_name',
            field=models.CharField(max_length=250, null=True, verbose_name='child_seat name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='seat_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='child_seat name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='seat_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='child_seat name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='seat_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='child_seat name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='seat_num',
            field=models.CharField(max_length=250, null=True, verbose_name='child_seat price'),
        ),
        migrations.AddField(
            model_name='additional',
            name='second_name',
            field=models.CharField(max_length=250, null=True, verbose_name='second name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='second_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='second name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='second_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='second name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='second_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='second name'),
        ),
        migrations.AddField(
            model_name='additional',
            name='second_num',
            field=models.CharField(max_length=250, null=True, verbose_name='second price'),
        ),
        migrations.AlterField(
            model_name='additional',
            name='winter_name',
            field=models.CharField(max_length=250, null=True, verbose_name='winter name'),
        ),
        migrations.AlterField(
            model_name='additional',
            name='winter_num',
            field=models.CharField(max_length=250, null=True, verbose_name='winter price'),
        ),
    ]
