# Generated by Django 5.0.2 on 2024-03-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_additional_add_num_additional_booster_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slayder',
            name='background',
        ),
        migrations.AddField(
            model_name='reservation',
            name='engine_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='engine name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='engine_name_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='engine name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='engine_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='engine name'),
        ),
        migrations.AddField(
            model_name='slayder',
            name='button_name',
            field=models.CharField(max_length=250, null=True, verbose_name='button name'),
        ),
        migrations.AddField(
            model_name='slayder',
            name='car_name',
            field=models.CharField(max_length=250, null=True, verbose_name='car name'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='car_about',
            field=models.CharField(max_length=250, verbose_name='car name'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='car_about_en',
            field=models.CharField(max_length=250, null=True, verbose_name='car name'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='car_about_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='car name'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='car_about_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='car name'),
        ),
        migrations.AlterField(
            model_name='slayder',
            name='img',
            field=models.ImageField(upload_to='Slayder/', verbose_name='car image'),
        ),
    ]
