# Generated by Django 5.0.1 on 2024-02-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_header_language_logo_en_header_language_logo_hy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='page3',
            field=models.CharField(max_length=250, verbose_name='pag name'),
        ),
        migrations.AlterField(
            model_name='header',
            name='page3_en',
            field=models.CharField(max_length=250, null=True, verbose_name='pag name'),
        ),
        migrations.AlterField(
            model_name='header',
            name='page3_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='pag name'),
        ),
        migrations.AlterField(
            model_name='header',
            name='page3_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='pag name'),
        ),
    ]
