# Generated by Django 5.0.1 on 2024-02-24 16:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_header_page3_alter_header_page3_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etap1',
            name='background',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, verbose_name='background color'),
        ),
    ]
