# Generated by Django 5.0.1 on 2024-02-24 16:17

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_etap1_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slayder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='main name')),
                ('background', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, verbose_name='background color')),
                ('img', models.ImageField(upload_to='etap1/', verbose_name='slayder image')),
            ],
        ),
        migrations.DeleteModel(
            name='Etap1',
        ),
    ]
