# Generated by Django 5.0 on 2023-12-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter car name', max_length=250, verbose_name='Car name')),
                ('price', models.PositiveIntegerField(help_text='Enter car price', verbose_name='Car price')),
                ('img', models.ImageField(help_text='Enter car image', upload_to='', verbose_name='Car image')),
            ],
        ),
    ]
