# Generated by Django 5.0.1 on 2024-01-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_header_name_en_header_name_hy_header_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='page2_en',
            field=models.CharField(max_length=250, null=True, verbose_name='page2 name'),
        ),
        migrations.AddField(
            model_name='header',
            name='page2_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='page2 name'),
        ),
        migrations.AddField(
            model_name='header',
            name='page2_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='page2 name'),
        ),
        migrations.AddField(
            model_name='header',
            name='page3_en',
            field=models.CharField(max_length=250, null=True, verbose_name='page3 name'),
        ),
        migrations.AddField(
            model_name='header',
            name='page3_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='page3 name'),
        ),
        migrations.AddField(
            model_name='header',
            name='page3_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='page3 name'),
        ),
        migrations.AddField(
            model_name='header',
            name='search_en',
            field=models.CharField(max_length=250, null=True, verbose_name='search name'),
        ),
        migrations.AddField(
            model_name='header',
            name='search_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='search name'),
        ),
        migrations.AddField(
            model_name='header',
            name='search_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='search name'),
        ),
    ]
