# Generated by Django 5.0.1 on 2024-01-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_header_page2_en_header_page2_hy_header_page2_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etap1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='main name')),
                ('name_hy', models.CharField(max_length=250, null=True, verbose_name='main name')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='main name')),
                ('name_en', models.CharField(max_length=250, null=True, verbose_name='main name')),
                ('about', models.CharField(max_length=250, verbose_name='main text')),
                ('about_hy', models.CharField(max_length=250, null=True, verbose_name='main text')),
                ('about_ru', models.CharField(max_length=250, null=True, verbose_name='main text')),
                ('about_en', models.CharField(max_length=250, null=True, verbose_name='main text')),
                ('bd_img', models.ImageField(upload_to='etap1/', verbose_name='main image')),
                ('img', models.ImageField(upload_to='etap1/', verbose_name='main image')),
            ],
            options={
                'verbose_name': 'Etap1',
                'verbose_name_plural': 'Etapner',
            },
        ),
    ]
