# Generated by Django 5.0.1 on 2024-01-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_etap1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='choise name')),
                ('name_hy', models.CharField(max_length=250, null=True, verbose_name='choise name')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='choise name')),
                ('name_en', models.CharField(max_length=250, null=True, verbose_name='choise name')),
                ('car_logo', models.ImageField(upload_to='Choise/', verbose_name='car image')),
                ('car_about', models.CharField(max_length=250, verbose_name='Car name')),
                ('car_about_hy', models.CharField(max_length=250, null=True, verbose_name='Car name')),
                ('car_about_ru', models.CharField(max_length=250, null=True, verbose_name='Car name')),
                ('car_about_en', models.CharField(max_length=250, null=True, verbose_name='Car name')),
            ],
        ),
    ]
