# Generated by Django 5.0.1 on 2024-02-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_header_name_en_remove_header_name_hy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='language_logo_en',
            field=models.ImageField(null=True, upload_to='header/', verbose_name='language_logo'),
        ),
        migrations.AddField(
            model_name='header',
            name='language_logo_hy',
            field=models.ImageField(null=True, upload_to='header/', verbose_name='language_logo'),
        ),
        migrations.AddField(
            model_name='header',
            name='language_logo_ru',
            field=models.ImageField(null=True, upload_to='header/', verbose_name='language_logo'),
        ),
    ]
